### ISSUE TITLE
[Chef] Skip update if services running

### ISSUE THREAD

**Issue by aloralove** [acep-uaf/camio-meter-streams#168]
Before updating the stream or archive software, the cookbook should check to see if the services are running. If so then skip the update till the next chef-client run.

**Comment by nicolemah99** [comment]
I've added a service helper to check whether the camio-meter-streams is running.
- `service_active?` currently returns true if the exit code is 0 for `is-active`
- I haven't added exit code 3 for activating because when I did `systemctl is-active camio-meter-streams.service` on ot-dev it was inactive (as expected) but the return code was 3.
I should probably add a check for the archive service.
